name: Generate Keystore
on:
  workflow_dispatch:
    inputs:
      keystore_password:
        description: 'Password untuk keystore & key (bikin sendiri, jangan pakai yang lama)'
        required: true
      key_alias:
        description: 'Alias key'
        required: true
        default: 'voidedit'

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Mask password di log
        run: echo "::add-mask::${{ inputs.keystore_password }}"

      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore voidedit.jks -alias "${{ inputs.key_alias }}" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=VoidEdit,O=VoidEdit,C=ID" \
            -storepass "${{ inputs.keystore_password }}" \
            -keypass "${{ inputs.keystore_password }}"
          base64 -w 0 voidedit.jks > keystore.b64

      - uses: actions/upload-artifact@v4
        with:
          name: keystore-b64
          path: keystore.b64
